baseurl = "http://en.cayco.pl/"
languageCode = "en-US"
title = "Krzysztof Kajkowski: adventure riding and trips. By motorcycle and everything else."
theme = "cayco"
disqusShortname = "krzysztofkajkowski"
pluralizelisttitles = "false"
contentdir = "content/en"
publishdir = "public/en"
    
[taxonomies]
tag = "tags"
place = "places"

[params]
    description = "Homepage for Krzysztof Kajkowski (cayco). You can find detailed descriptions of my motorcycle adventure trips. I also write on testing some outdoor gear. You will find all necessary information on what to take on a trip."
    locale = "ja-JP"