baseurl = "https://www.cayco.pl/"
languageCode = "pl-PL"
title = "cayco"
theme = "cayco"
disqusShortname = "krzysztofkajkowski"

pluralizelisttitles = "false"


[taxonomies]
tag = "tagi"
miejsce = "miejsca"