baseurl = "https://www.cayco.pl/"
languageCode = "pl-PL"
title = "Krzysztof Kajkowski: podróże i wyprawy. Motocyklowe i nie tylko."
theme = "cayco"
disqusShortname = "krzysztofkajkowski"
pluralizelisttitles = "false"
contentdir = "content/pl"
publishdir = "public/"

[taxonomies]
tag = "tagi"
miejsce = "miejsca"

[params]
    description = "Strona domowa Krzysztof Kajkowski (cayco). Relacje z wypraw motocyklowych i innych. Opisy sprzętu wyprawowego. Porady - co zabrać ze sobą na wyjazd do... Fotografia podróżna. Zapraszam!"
